### ISSUE TITLE
请问使用装饰器@provider(key)注入的依赖如何获取?

### ISSUE THREAD

**Issue by zzyyzz1992** [midwayjs/injection#15]
Midway里面的Container或者MidwayContainer如果new一个的话里面是空的.
请问如何获取使用Midway的provider装饰对应的Container?
谢谢!

**Comment by zzyyzz1992** [comment]
找到了,方便后来人参考:
[动态函数注入](https://midwayjs.org/injection/guide.html#%E5%8A%A8%E6%80%81%E5%87%BD%E6%95%B0%E6%B3%A8%E5%85%A5)
```
export function containerFactory(context: IApplicationContext) {
    return async (name: string) => {
        return await context.getAsync(name);
    };
};
providerWrapper([
    {
        id: 'containerFactory',
        provider: containerFactory
    }
]);
```
```
 @inject('containerFactory')
    containerFactory;
```

**Comment by czy88840616** [comment]
如果是请求作用域，也可以通过 ctx.requestContext 获取，静态作用域，使用 app.applicationContext，不过一般情况下用不到。
