### ISSUE TITLE
您好，请问如何使用autowire实例化有参构造函数的对象

### ISSUE THREAD

**Issue by feiyueXH** [midwayjs/injection#47]

**Comment by kurten** [comment]
可以使用构造器注入的方式，midway 支持 config、logger、class 这样的实例注入
https://midwayjs.org/midway/ioc.html#%E6%9E%84%E9%80%A0%E5%99%A8%E6%B3%A8%E5%85%A5

**Comment by lubezhang** [comment]
如果不使用注入的方式，只用容器的api，如何做？ 

是在bind阶段做？ 还是在get阶段做？

**Comment by czy88840616** [comment]
container.get() or container.getAsync()
