### ISSUE TITLE
`Scope` type refinement

### ISSUE THREAD

**Issue by siqiwith** [midwayjs/injection#5]
When `createObjectDependencyTree` method is called, the param `scope: definition.scope` is passed to `dependencyMap `.
https://github.com/midwayjs/injection/blob/58ae8ef6fbee8844dc1f0a3749577284c766bfdf/src/factory/applicationContext.ts#L296

But there is no definition for `scope` in `interface IObjectDefinition` 
https://github.com/midwayjs/injection/blob/58ae8ef6fbee8844dc1f0a3749577284c766bfdf/src/factory/applicationContext.ts#L250

https://github.com/midwayjs/injection/blob/58ae8ef6fbee8844dc1f0a3749577284c766bfdf/src/interfaces.ts#L44

I guess the `scope` type should be `Scope` instead of `IScopeEnum`?
https://github.com/midwayjs/injection/blob/58ae8ef6fbee8844dc1f0a3749577284c766bfdf/src/interfaces.ts#L201

Suggest to remove `IScopeEnum` from `interfaces.ts` and change `scope.ts` to export an enum.
```
export enum ScopeEnum {
  Singleton = 'Singleton',
  Request = 'Request',
  Prototype = 'Prototype',
};
```

Pull request #6  created...

**Comment by czy88840616** [comment]
looks great.
